import { promises as fs } from 'node:fs';
import path from 'node:path';
import fse from 'fs-extra';

import type { Answers } from './interview.types.js';
import type { Stage, StageContext, StageResult } from './scaffold.types.js';

const CHECKLIST_PATH = 'docs/checklist.md';

interface ChecklistItem {
  title: string;
  files: string[];
  status: 'wired' | 'stub';
  note?: string;
}

const buildItems = (answers: Answers): ChecklistItem[] => {
  const has = (mod: 'pinecone' | 'upstash' | 'resend'): boolean =>
    answers.optionalModules.includes(mod);

  return [
    { title: 'Auth', files: ['packages/auth', 'apps/web/middleware.ts', 'apps/web/app/api/webhooks/clerk/route.ts'], status: 'wired' },
    { title: 'Database', files: ['packages/db/prisma/schema.prisma', 'packages/db/src/client.ts'], status: 'wired' },
    { title: 'Payments', files: ['packages/payments', 'apps/web/app/api/webhooks/stripe/route.ts'], status: 'wired' },
    { title: 'Security', files: ['apps/web/middleware.ts', 'apps/web/next.config.ts'], status: 'wired' },
    { title: 'Frontend', files: ['apps/web/app', 'packages/ui'], status: 'wired' },
    { title: 'Backend', files: ['apps/web/app/api'], status: 'wired' },
    {
      title: 'Notifications',
      files: ['packages/email'],
      status: has('resend') ? 'wired' : 'stub',
      note: has('resend') ? undefined : 'Resend module skipped at scaffold time.',
    },
    { title: 'Analytics', files: ['packages/analytics', 'apps/web/app/layout.tsx'], status: 'wired' },
    { title: 'Error handling', files: ['packages/core/src/errors.ts', 'apps/web/app/error.tsx'], status: 'wired' },
    { title: 'Logging', files: ['packages/observability/src/logger.ts', 'apps/web/instrumentation.ts'], status: 'wired' },
    { title: 'File storage', files: ['packages/db/src/storage.ts'], status: 'wired' },
    { title: 'Settings', files: ['apps/web/app/(app)/settings/page.tsx'], status: 'wired' },
    { title: 'Onboarding', files: ['apps/web/app/(app)/onboarding/page.tsx'], status: 'wired' },
    { title: 'Performance', files: ['apps/web/next.config.ts'], status: 'wired' },
    { title: 'Landing page', files: ['apps/web/app/(marketing)/page.tsx'], status: 'wired' },
  ];
};

const renderItem = (i: number, item: ChecklistItem): string => {
  const checkbox = item.status === 'wired' ? '[x]' : '[ ]';
  const files = item.files.map((f) => `\`${f}\``).join(', ');
  const note = item.note ? ` _(${item.note})_` : '';
  return `${i}. ${checkbox} **${item.title}** — ${files}${note}`;
};

/** Pure render of the project-tailored launch checklist. */
export const renderChecklist = (answers: Answers): string => {
  const lines = [
    `# ${answers.projectName} — launch checklist`,
    '',
    `_Generated by scaffoldo. Each item links to the file(s) that wire it._`,
    '',
    ...buildItems(answers).map((item, idx) => renderItem(idx + 1, item)),
    '',
  ];
  return lines.join('\n');
};

export const projectChecklistStage: Stage = {
  name: 'project-checklist',
  apply: async (ctx: StageContext): Promise<StageResult> => {
    const file = path.join(ctx.targetDir, CHECKLIST_PATH);
    if (!(await fse.pathExists(file))) return { filesWritten: 0 };
    await fs.writeFile(file, renderChecklist(ctx.answers));
    return { filesWritten: 1 };
  },
};
